### ISSUE TITLE
"======" in front of every chat message

### ISSUE THREAD

**Issue by AnonymousPuppy** [Eximius88/ModularPowersuitsAddons#20]
Using forge .1231, a custom modpack, MPS 0.11.0.172, numina 0.4.0.98, slick util, and MPSA 901. This only occurs on a server, and the server I used was running cauldron 1.1231.04.209. All of the mods are the latest versions. The issue is that a "======" shows up in front of every chat message. I pinpointed the issue down to MPSA. There is no crash, and there isn't anything out of the ordinary in the server or client console. Please look into this whenever you can, thank you.

**Comment by Pinkbyte** [comment]
Quick look at the code, probably it's because src/main/resources/assets/{powersuits,powersuitaddons}/lang/en_US.lang
 files contains ===== now, because of commit f61ae341baa48e0882120cafa65ec5aefb0ae984

It seems that this was accident during commit conflict resolution, but i can be wrong.

Also, this occurs on client side, so, this will happen regardless of it's installation on server

Update: yep, i was right. I fixed that files, repacked .jar and issue is gone

**Comment by AnonymousPuppy** [comment]
Awesome! Do you think I could have the .jar file? I don't know when Eximius88 will release the next update, and I have no idea how to do it myself. Thanks

**Comment by Pinkbyte** [comment]
http://www.filedropper.com/powersuitaddons-1710-901-lang-fix

Not sure how much time this link will last, i hope that Eximius88 will deal with this soon.

@Eximius88, is it helps if i will send you pull request?

**Comment by AnonymousPuppy** [comment]
Thanks man!

**Comment by Eximius88** [comment]
It was an issue caused by source tree when I made that commit. It didn't like something about that file, and I didn't read the quick fix it proposed. Lesson learned, I have fixed it now.
