### ISSUE TITLE
Crash on startup with Applied Energistics RV2 Stable

### ISSUE THREAD

**Issue by SephirothWS** [Eximius88/ModularPowersuitsAddons#33]
Yes, I know this is a duplicate of #32. However, here is a crash report without Optifine, but I do have Fastcraft installed. From what I know, MPS is built against AE2 RV1's API, and since RV2 is now considered stable, ... I think we might need an update.

https://gist.github.com/SephirothWS/59bfc83b06d1a68cc97b

**Comment by misterhaan** [comment]
according to (closed) pull request #30, ae2 rv2 changed casing and fixed spelling on openWirelessTerminalGui (rv1 has OpenWirelessTermainlGui), so that's what’s failing.  i’ve temporarily removed mpsa from my modpack but am missing the kinetic generator and clock enough i'm considering building my own rv2-compatible jar.  it’s been a long time since i’ve done java development...

**Comment by Daeturen** [comment]
If you manage to create your own rv2-compatible.jar, can you give it to me please ?
